// TOEIC Speaking 400 핵심 표현 시드 데이터
// 카테고리별 영어 입문~중급(400~700점) 학습자가 일반 회화 도달까지 반복 학습할 가치가 있는 문장
import type { InsertToeic } from "@shared/schema";

type Pair = [string, string];

const groups: { category: string; items: Pair[] }[] = [
  {
    category: "자기소개",
    items: [
      ["저는 한국에서 왔습니다.", "I'm from Korea."],
      ["만나서 반갑습니다.", "Nice to meet you."],
      ["저는 공무원으로 일하고 있습니다.", "I work as a public official."],
      ["제 이름은 ___입니다.", "My name is ___."],
      ["저는 영어를 공부하고 있습니다.", "I'm studying English."],
      ["취미는 농구입니다.", "My hobby is basketball."],
      ["저는 안양에 살고 있습니다.", "I live in Anyang."],
      ["가족은 모두 네 명입니다.", "There are four people in my family."],
      ["저는 박사 과정에 있습니다.", "I'm a PhD candidate."],
      ["만나서 정말 영광입니다.", "It's a pleasure to meet you."],
      ["당신에 대해 더 듣고 싶습니다.", "I'd like to hear more about you."],
      ["저는 도시 행정 분야에서 일합니다.", "I work in municipal administration."],
      ["저는 한국 경기도 출신입니다.", "I'm originally from Gyeonggi Province, Korea."],
      ["저는 오랫동안 영어를 공부해 왔습니다.", "I've been studying English for a long time."],
      ["주요 관심 분야는 환경 정책입니다.", "My main interest is environmental policy."],
    ],
  },
  {
    category: "일상회화",
    items: [
      ["오늘 기분이 어떠세요?", "How are you feeling today?"],
      ["오늘은 정말 바빴어요.", "I had a really busy day today."],
      ["주말 잘 보내세요.", "Have a great weekend."],
      ["내일 봬요.", "See you tomorrow."],
      ["오랜만이에요.", "Long time no see."],
      ["요즘 어떻게 지내세요?", "How have you been these days?"],
      ["곧 연락드릴게요.", "I'll get in touch with you soon."],
      ["부탁 하나만 드려도 될까요?", "Can I ask you a favor?"],
      ["다시 한 번 말씀해 주시겠어요?", "Could you say that again, please?"],
      ["천천히 말씀해 주세요.", "Could you speak more slowly, please?"],
      ["이해했습니다.", "I understand."],
      ["잘 모르겠습니다.", "I'm not sure."],
      ["정말 감사합니다.", "Thank you very much."],
      ["천만에요.", "You're welcome."],
      ["죄송합니다.", "I'm sorry."],
      ["괜찮습니다.", "That's all right."],
      ["좋은 아침입니다.", "Good morning."],
      ["좋은 밤 되세요.", "Good night."],
      ["오늘 어떠셨어요?", "How was your day?"],
      ["조심히 가세요.", "Have a safe trip home."],
      ["수고하셨습니다.", "Thanks for your hard work."],
      ["잘 지내고 있어요.", "I'm doing well."],
      ["별일 없어요.", "Nothing much."],
      ["진심이에요.", "I mean it."],
      ["농담이에요.", "I'm just kidding."],
      ["혹시 시간 있으세요?", "Do you have a moment?"],
      ["나중에 얘기해도 될까요?", "Can we talk later?"],
      ["급하지 않아요.", "It's not urgent."],
      ["저도 마찬가지예요.", "Same here."],
      ["좋은 생각이에요.", "That's a good idea."],
    ],
  },
  {
    category: "사진묘사",
    items: [
      ["사진 속에는 두 명이 있습니다.", "There are two people in the picture."],
      ["남자가 책을 읽고 있습니다.", "A man is reading a book."],
      ["여자가 컴퓨터 앞에 앉아 있습니다.", "A woman is sitting in front of a computer."],
      ["사람들이 회의를 하고 있습니다.", "People are having a meeting."],
      ["테이블 위에 노트북이 놓여 있습니다.", "There is a laptop on the table."],
      ["창밖으로 나무가 보입니다.", "I can see trees through the window."],
      ["벽에 그림이 걸려 있습니다.", "A painting is hanging on the wall."],
      ["전체적으로 사무실 분위기입니다.", "Overall, it looks like an office."],
      ["사람들이 즐거워 보입니다.", "The people look happy."],
      ["커피잔이 손에 들려 있습니다.", "A coffee cup is in his hand."],
      ["배경에는 건물이 보입니다.", "I can see a building in the background."],
      ["오른쪽에는 꽃병이 있습니다.", "There is a vase on the right side."],
      ["사진 가운데에 책상이 있습니다.", "There is a desk in the middle of the picture."],
      ["남자가 안경을 끼고 있습니다.", "The man is wearing glasses."],
      ["여자가 미소 짓고 있습니다.", "The woman is smiling."],
      ["거리에 사람들이 많이 보입니다.", "There are many people on the street."],
      ["하늘이 매우 맑습니다.", "The sky is very clear."],
      ["나무들이 줄지어 서 있습니다.", "Trees are lined up in a row."],
      ["자동차들이 도로에 주차되어 있습니다.", "Cars are parked on the road."],
      ["사진 왼쪽에는 의자가 있습니다.", "There is a chair on the left side of the picture."],
      ["바닥에는 카펫이 깔려 있습니다.", "There is a carpet on the floor."],
      ["화면에는 그래프가 표시되어 있습니다.", "A graph is displayed on the screen."],
      ["남자가 전화 통화를 하고 있습니다.", "A man is talking on the phone."],
      ["서점 안 풍경처럼 보입니다.", "It looks like a scene inside a bookstore."],
      ["창문 밖으로 햇빛이 들어옵니다.", "Sunlight is coming through the window."],
    ],
  },
  {
    category: "의견제시",
    items: [
      ["제 생각에는 그것이 좋은 아이디어입니다.", "In my opinion, that's a good idea."],
      ["저는 동의합니다.", "I agree with that."],
      ["저는 동의하지 않습니다.", "I don't agree with that."],
      ["다른 관점에서 보면 어떨까요?", "How about looking at it from a different angle?"],
      ["가장 중요한 것은 시간 관리입니다.", "The most important thing is time management."],
      ["몇 가지 이유가 있습니다.", "There are a few reasons."],
      ["첫째로, 비용이 절감됩니다.", "First of all, it reduces costs."],
      ["둘째로, 효율성이 높아집니다.", "Secondly, efficiency increases."],
      ["결론적으로 저는 찬성합니다.", "In conclusion, I'm in favor of it."],
      ["이 점에 대해 어떻게 생각하세요?", "What do you think about this point?"],
      ["장점과 단점을 모두 고려해야 합니다.", "We need to consider both pros and cons."],
      ["사람마다 의견이 다를 수 있습니다.", "Opinions may vary from person to person."],
      ["좀 더 구체적으로 말씀드리자면…", "To be more specific..."],
      ["예를 들어 보겠습니다.", "Let me give you an example."],
      ["제 경험으로는…", "In my experience..."],
      ["연구에 따르면…", "According to research..."],
      ["반대로 생각해 보면…", "On the contrary..."],
      ["요컨대…", "In short..."],
      ["저도 같은 생각입니다.", "I feel the same way."],
      ["부분적으로 동의합니다.", "I partly agree."],
      ["타당한 지적입니다.", "That's a fair point."],
      ["강력히 반대합니다.", "I strongly disagree."],
      ["중립적인 입장입니다.", "I'm neutral on this."],
      ["저는 그렇게 생각하지 않습니다.", "I don't think so."],
      ["전적으로 동감합니다.", "I couldn't agree more."],
    ],
  },
  {
    category: "비즈니스/직장",
    items: [
      ["회의는 오후 2시에 시작합니다.", "The meeting starts at 2 p.m."],
      ["보고서를 검토해 주시겠어요?", "Could you review the report?"],
      ["내일까지 자료를 보내드리겠습니다.", "I'll send you the materials by tomorrow."],
      ["일정을 변경할 수 있을까요?", "Could we reschedule?"],
      ["회의실을 예약했습니다.", "I've booked the meeting room."],
      ["프로젝트 마감일이 다음 주입니다.", "The project deadline is next week."],
      ["담당자에게 연결해 드리겠습니다.", "I'll connect you with the person in charge."],
      ["문의 사항이 있으면 알려주세요.", "Please let me know if you have any questions."],
      ["계약서를 확인해 보겠습니다.", "Let me check the contract."],
      ["예산을 다시 검토해야 합니다.", "We need to review the budget again."],
      ["회의 안건을 공유해 주세요.", "Please share the meeting agenda."],
      ["출장 일정을 확정했습니다.", "I've confirmed the business trip schedule."],
      ["고객의 요구를 우선시해야 합니다.", "We should prioritize the client's needs."],
      ["분기별 실적이 향상되었습니다.", "Quarterly performance has improved."],
      ["현재 진행 상황은 어떻게 됩니까?", "What's the current status?"],
      ["결재가 완료되었습니다.", "The approval has been completed."],
      ["회의록을 공유드리겠습니다.", "I'll share the meeting minutes."],
      ["다음 단계를 정리해 봅시다.", "Let's outline the next steps."],
      ["우선순위를 정해야 합니다.", "We need to set priorities."],
      ["실행 가능성을 검토 중입니다.", "We're reviewing the feasibility."],
      ["경영진의 승인을 기다리고 있습니다.", "We're waiting for management's approval."],
      ["부서 간 협업이 필요합니다.", "We need collaboration across departments."],
      ["발표 자료를 준비하고 있습니다.", "I'm preparing the presentation."],
      ["프레젠테이션을 시작하겠습니다.", "Let me begin the presentation."],
      ["질문이 있으시면 마지막에 받겠습니다.", "I'll take questions at the end."],
      ["연락처를 알려 주시겠어요?", "Could you give me your contact information?"],
      ["메일로 다시 보내드리겠습니다.", "I'll send it again by email."],
      ["참석 가능 여부를 확인 부탁드립니다.", "Please confirm your attendance."],
      ["프로젝트가 순조롭게 진행되고 있습니다.", "The project is going smoothly."],
      ["문제를 즉시 해결하겠습니다.", "I'll resolve the issue right away."],
    ],
  },
  {
    category: "여행",
    items: [
      ["공항까지 가는 데 얼마나 걸리나요?", "How long does it take to get to the airport?"],
      ["호텔을 예약했습니다.", "I've booked a hotel."],
      ["여권을 보여주시겠어요?", "May I see your passport?"],
      ["수하물을 분실했습니다.", "I lost my luggage."],
      ["관광 명소를 추천해 주시겠어요?", "Could you recommend any tourist attractions?"],
      ["택시를 불러 주시겠어요?", "Could you call a taxi for me?"],
      ["환율이 어떻게 되나요?", "What is the exchange rate?"],
      ["체크인 시간은 몇 시인가요?", "What time is check-in?"],
      ["룸 서비스를 부탁드립니다.", "I'd like to order room service."],
      ["지하철역이 어디인가요?", "Where is the subway station?"],
      ["편도 티켓 한 장 주세요.", "One one-way ticket, please."],
      ["왕복 항공권을 예약했습니다.", "I've booked a round-trip ticket."],
      ["탑승 게이트가 어디인가요?", "Where is the boarding gate?"],
      ["수속은 어디서 하나요?", "Where do I check in?"],
      ["면세점은 어디 있나요?", "Where is the duty-free shop?"],
      ["환승 시간이 얼마나 되나요?", "How long is the layover?"],
      ["관광지도를 받을 수 있나요?", "Can I get a tourist map?"],
      ["사진 좀 찍어 주시겠어요?", "Could you take a picture for me?"],
      ["기차는 몇 시에 출발하나요?", "What time does the train leave?"],
      ["박물관 입장료는 얼마인가요?", "How much is the museum admission?"],
      ["가이드 투어가 있나요?", "Is there a guided tour?"],
      ["렌터카를 예약하고 싶습니다.", "I'd like to rent a car."],
      ["이 동네에 추천 식당이 있나요?", "Are there any recommended restaurants nearby?"],
      ["여행자 보험에 가입했습니다.", "I have travel insurance."],
      ["관광 안내소가 어디 있나요?", "Where is the tourist information center?"],
    ],
  },
  {
    category: "음식/식당",
    items: [
      ["메뉴를 보여 주시겠어요?", "Could I see the menu?"],
      ["오늘의 추천 메뉴는 무엇인가요?", "What's today's special?"],
      ["저는 채식주의자입니다.", "I'm a vegetarian."],
      ["덜 맵게 해 주세요.", "Less spicy, please."],
      ["계산서 부탁드립니다.", "Could I have the bill, please?"],
      ["테이블을 예약하고 싶습니다.", "I'd like to reserve a table."],
      ["음식이 정말 맛있었어요.", "The food was really delicious."],
      ["포장해 주시겠어요?", "Could you pack this to go?"],
      ["물 한 잔 더 주시겠어요?", "Could I have another glass of water?"],
      ["디저트는 무엇이 있나요?", "What desserts do you have?"],
      ["견과류 알레르기가 있어요.", "I'm allergic to nuts."],
      ["주문할 준비가 되었습니다.", "We're ready to order."],
      ["오늘 영업하나요?", "Are you open today?"],
      ["몇 시까지 영업하나요?", "What time do you close?"],
      ["인분이 적당한가요?", "Is it a good portion size?"],
      ["오늘 자리가 있을까요?", "Do you have a table available tonight?"],
      ["창가 자리로 부탁드립니다.", "By the window, please."],
      ["카드와 현금 모두 가능합니까?", "Do you take both card and cash?"],
      ["서비스가 훌륭했습니다.", "The service was excellent."],
      ["다음에 또 오겠습니다.", "I'll come again next time."],
    ],
  },
  {
    category: "쇼핑",
    items: [
      ["이거 얼마예요?", "How much is this?"],
      ["다른 색상이 있나요?", "Do you have it in another color?"],
      ["입어볼 수 있을까요?", "Can I try it on?"],
      ["할인되나요?", "Is it on sale?"],
      ["카드 결제 가능한가요?", "Can I pay by card?"],
      ["영수증 주세요.", "Could I have the receipt?"],
      ["환불받고 싶습니다.", "I'd like a refund."],
      ["사이즈가 안 맞아요.", "It doesn't fit me."],
      ["선물 포장해 주시겠어요?", "Could you gift-wrap it?"],
      ["조금 더 둘러볼게요.", "I'll look around a bit more."],
      ["탈의실이 어디인가요?", "Where is the fitting room?"],
      ["좀 더 작은 사이즈 있나요?", "Do you have a smaller size?"],
      ["좀 더 큰 사이즈 있나요?", "Do you have a larger size?"],
      ["할인 쿠폰이 있어요.", "I have a discount coupon."],
      ["품질이 정말 좋네요.", "The quality is really good."],
      ["배송은 얼마나 걸리나요?", "How long does shipping take?"],
      ["반품 정책이 어떻게 되나요?", "What's your return policy?"],
      ["이거 신상품인가요?", "Is this a new arrival?"],
      ["가격을 깎아 주실 수 있나요?", "Could you give me a discount?"],
      ["계산해 주세요.", "I'd like to check out, please."],
    ],
  },
  {
    category: "감정/관계",
    items: [
      ["정말 기쁩니다.", "I'm really happy."],
      ["걱정하지 마세요.", "Don't worry."],
      ["축하합니다.", "Congratulations."],
      ["힘내세요.", "Cheer up."],
      ["많이 보고 싶었어요.", "I missed you a lot."],
      ["당신의 도움에 감사드립니다.", "I appreciate your help."],
      ["좋은 하루 보내세요.", "Have a nice day."],
      ["행운을 빕니다.", "Good luck."],
      ["덕분입니다.", "It's all thanks to you."],
      ["함께해서 즐거웠어요.", "It was a pleasure being with you."],
      ["많이 실망했어요.", "I was very disappointed."],
      ["조금 긴장돼요.", "I'm a bit nervous."],
      ["흥분돼요.", "I'm excited."],
      ["정말 감동했어요.", "I was really moved."],
      ["고마운 마음 잊지 않을게요.", "I won't forget your kindness."],
      ["진심으로 감사드립니다.", "I sincerely thank you."],
      ["사과드립니다.", "I apologize."],
      ["용서해 주세요.", "Please forgive me."],
      ["이해해 주셔서 감사합니다.", "Thank you for understanding."],
      ["이 자리에 함께해서 영광입니다.", "It's an honor to be here with you."],
    ],
  },
  {
    category: "취미/여가",
    items: [
      ["주말에 보통 무엇을 하세요?", "What do you usually do on weekends?"],
      ["저는 농구를 좋아합니다.", "I like playing basketball."],
      ["주말에 영화를 봤어요.", "I watched a movie over the weekend."],
      ["맛집 탐방이 취미입니다.", "Exploring restaurants is my hobby."],
      ["요즘 어떤 책을 읽으세요?", "What kind of book are you reading these days?"],
      ["다큐멘터리 보는 것을 좋아합니다.", "I enjoy watching documentaries."],
      ["운동을 시작했습니다.", "I've started working out."],
      ["여행 계획을 세우고 있어요.", "I'm planning a trip."],
      ["새로운 식당을 발견했어요.", "I found a new restaurant."],
      ["주말은 가족과 보냅니다.", "I spend weekends with my family."],
      ["주식 투자에 관심이 있어요.", "I'm interested in stock investment."],
      ["요리하는 것을 즐겨요.", "I enjoy cooking."],
      ["헬스장에 정기적으로 다닙니다.", "I go to the gym regularly."],
      ["사진 찍는 것이 취미입니다.", "Taking photos is my hobby."],
      ["산책을 자주 합니다.", "I take walks often."],
      ["등산을 즐깁니다.", "I enjoy hiking."],
      ["악기를 연주할 줄 압니다.", "I can play a musical instrument."],
      ["넷플릭스로 드라마를 봐요.", "I watch dramas on Netflix."],
      ["주말마다 새로운 카페를 가요.", "I visit a new café every weekend."],
      ["팟캐스트를 즐겨 듣습니다.", "I enjoy listening to podcasts."],
    ],
  },
  {
    category: "회화 빈출표현",
    items: [
      ["바로 그거예요.", "That's exactly it."],
      ["말이 되네요.", "That makes sense."],
      ["나도 그래.", "Me too."],
      ["정말요?", "Really?"],
      ["놀랍네요.", "That's surprising."],
      ["솔직히 말하면…", "To be honest..."],
      ["어쨌든…", "Anyway..."],
      ["그런데 말이야…", "By the way..."],
      ["방금 뭐라고 하셨어요?", "What did you just say?"],
      ["좀 도와주실 수 있을까요?", "Could you give me a hand?"],
      ["급할 것 없어요.", "No rush."],
      ["문제없어요.", "No problem."],
      ["일이 좀 생겼어요.", "Something came up."],
      ["꼭 그렇진 않아요.", "Not necessarily."],
      ["곧 가겠습니다.", "I'll be right there."],
      ["거의 다 왔어요.", "I'm almost there."],
      ["조심해서 가세요.", "Take care."],
      ["쉬엄쉬엄 하세요.", "Take it easy."],
      ["계속 연락하고 지내요.", "Let's keep in touch."],
      ["그건 제 잘못이에요.", "That's my fault."],
      ["당연하죠.", "Of course."],
      ["전혀요.", "Not at all."],
      ["그럴 줄 알았어요.", "I figured."],
      ["글쎄요.", "Well, I'm not sure."],
      ["그것도 좋네요.", "That works too."],
      ["좀 생각해 볼게요.", "Let me think about it."],
      ["나중에 알려 줄게요.", "I'll let you know later."],
      ["언제든 말씀하세요.", "Just let me know anytime."],
      ["혹시 모를 일이죠.", "You never know."],
      ["참고로 말씀드리면…", "For your information..."],
    ],
  },
  {
    category: "전화/이메일",
    items: [
      ["여보세요?", "Hello?"],
      ["___ 씨 부탁드립니다.", "May I speak to ___, please?"],
      ["누구신가요?", "Who's calling, please?"],
      ["메시지를 남기시겠어요?", "Would you like to leave a message?"],
      ["나중에 다시 전화드릴게요.", "I'll call you back later."],
      ["연결해 드리겠습니다.", "I'll put you through."],
      ["통화 가능하세요?", "Are you available to talk?"],
      ["잘 안 들립니다.", "I can hardly hear you."],
      ["전화를 다시 걸어 주시겠어요?", "Could you call back, please?"],
      ["안부 전해 주세요.", "Please give my regards."],
      ["메일로 답변드리겠습니다.", "I'll get back to you by email."],
      ["첨부 파일을 확인해 주세요.", "Please find the attached file."],
      ["회신 부탁드립니다.", "Please reply at your earliest convenience."],
      ["회의 내용을 요약해 보내드립니다.", "I'm sending you a summary of the meeting."],
      ["빠른 회신 감사드립니다.", "Thank you for your prompt reply."],
      ["문의 주셔서 감사합니다.", "Thank you for your inquiry."],
      ["요청하신 자료입니다.", "Here are the materials you requested."],
      ["수신 확인 부탁드립니다.", "Please confirm receipt."],
      ["오해가 있었던 것 같습니다.", "There seems to have been a misunderstanding."],
      ["다시 한 번 확인 부탁드립니다.", "Please double-check."],
    ],
  },
  {
    category: "공공/행정",
    items: [
      ["민원을 접수하고 싶습니다.", "I'd like to file a civil complaint."],
      ["이 신청서는 어떻게 작성하나요?", "How do I fill out this application form?"],
      ["담당 부서가 어디인가요?", "Which department handles this?"],
      ["서류를 제출하러 왔습니다.", "I'm here to submit some documents."],
      ["증명서를 발급받고 싶습니다.", "I'd like to get a certificate issued."],
      ["대기 번호표를 받으세요.", "Please take a number ticket."],
      ["이 절차는 얼마나 걸리나요?", "How long does this process take?"],
      ["수수료는 얼마인가요?", "How much is the fee?"],
      ["신분증을 보여 주시겠어요?", "May I see your ID?"],
      ["이 양식은 무엇을 위한 것인가요?", "What is this form for?"],
      ["조례에 근거하여 처리됩니다.", "It's processed based on the ordinance."],
      ["관련 규정을 확인해 보겠습니다.", "I'll check the related regulations."],
      ["접수가 완료되었습니다.", "Your application has been received."],
      ["처리 결과는 문자로 안내됩니다.", "You'll be notified of the result by text."],
      ["관할 부서로 이관되었습니다.", "It has been transferred to the responsible department."],
      ["공식 답변은 서면으로 드립니다.", "An official response will be provided in writing."],
      ["민원실은 1층에 있습니다.", "The civil affairs office is on the first floor."],
      ["예산 편성에 반영하겠습니다.", "We'll reflect it in the budget."],
      ["검토 후 회신드리겠습니다.", "I'll get back to you after review."],
      ["조례안을 발의하였습니다.", "We've proposed the ordinance bill."],
    ],
  },
  {
    category: "자기개발/학습",
    items: [
      ["저는 매일 영어를 공부합니다.", "I study English every day."],
      ["꾸준함이 가장 중요합니다.", "Consistency is the most important thing."],
      ["새로운 것을 배우는 게 즐겁습니다.", "I enjoy learning new things."],
      ["목표를 세우는 것이 도움이 됩니다.", "Setting goals helps me."],
      ["저는 천천히 발전하고 있습니다.", "I'm improving slowly."],
      ["계속 도전하고 있습니다.", "I keep challenging myself."],
      ["실수를 통해 배웁니다.", "I learn from my mistakes."],
      ["연습이 완벽을 만듭니다.", "Practice makes perfect."],
      ["한 단계씩 나아가고 있습니다.", "I'm taking it step by step."],
      ["피드백을 받는 것이 중요합니다.", "Receiving feedback is important."],
      ["저는 자기개발에 시간을 투자합니다.", "I invest time in self-improvement."],
      ["좋은 습관을 만들고 싶습니다.", "I want to build good habits."],
      ["학습 자료를 정리합니다.", "I organize my study materials."],
      ["하루 한 시간씩 공부합니다.", "I study one hour a day."],
      ["요즘 영작 연습을 하고 있어요.", "I've been practicing English writing lately."],
      ["발음 교정에 신경 쓰고 있습니다.", "I'm focusing on pronunciation correction."],
      ["섀도잉 연습이 도움이 됩니다.", "Shadowing practice is helpful."],
      ["원어민과 대화 연습을 합니다.", "I practice speaking with native speakers."],
      ["듣기 실력이 많이 늘었습니다.", "My listening skills have improved a lot."],
      ["꾸준한 노력의 결과를 봅니다.", "I'm seeing results from steady effort."],
    ],
  },
  {
    category: "건강/일상",
    items: [
      ["감기에 걸렸어요.", "I caught a cold."],
      ["몸이 별로 좋지 않아요.", "I'm not feeling well."],
      ["병원에 가봐야 할 것 같아요.", "I think I need to see a doctor."],
      ["충분히 쉬세요.", "Get plenty of rest."],
      ["약을 처방받았어요.", "I got a prescription."],
      ["빨리 회복하시길 바랍니다.", "I hope you get well soon."],
      ["요즘 잠을 잘 못 자요.", "I haven't been sleeping well."],
      ["스트레스가 많아요.", "I'm under a lot of stress."],
      ["규칙적으로 운동하려고 해요.", "I try to exercise regularly."],
      ["식단을 관리하고 있어요.", "I'm watching my diet."],
      ["혈압이 좀 높아요.", "My blood pressure is a bit high."],
      ["꾸준한 운동이 중요해요.", "Regular exercise is important."],
      ["오늘은 피곤하네요.", "I'm tired today."],
      ["에너지가 충만해요.", "I'm full of energy."],
      ["기분 전환이 필요해요.", "I need a change of pace."],
    ],
  },
  {
    category: "교통/길찾기",
    items: [
      ["___까지 어떻게 가나요?", "How do I get to ___?"],
      ["여기서 멀어요?", "Is it far from here?"],
      ["걸어서 갈 수 있나요?", "Can I walk there?"],
      ["가장 빠른 길은 무엇인가요?", "What's the fastest way?"],
      ["다음 정류장에서 내릴게요.", "I'll get off at the next stop."],
      ["환승을 어디서 해야 하나요?", "Where do I transfer?"],
      ["몇 호선을 타야 하나요?", "Which line should I take?"],
      ["지도 앱을 켜 보세요.", "Try opening the map app."],
      ["내비게이션이 길을 알려줄 거예요.", "The GPS will guide you."],
      ["여기서 좌회전하세요.", "Turn left here."],
      ["곧장 가다가 우회전하세요.", "Go straight and then turn right."],
      ["횡단보도를 건너세요.", "Cross at the crosswalk."],
      ["택시를 잡아야겠어요.", "I'll grab a taxi."],
      ["도착 예정 시간이 어떻게 되나요?", "What's the estimated arrival time?"],
      ["길이 막혔어요.", "There's traffic congestion."],
    ],
  },
  {
    category: "문화/사회",
    items: [
      ["한국 문화에 관심이 있어요.", "I'm interested in Korean culture."],
      ["저는 전통 음식을 좋아합니다.", "I like traditional food."],
      ["요즘 한국 드라마가 인기예요.", "Korean dramas are popular these days."],
      ["문화 차이가 흥미롭습니다.", "Cultural differences are interesting."],
      ["서로의 문화를 존중해야 합니다.", "We should respect each other's cultures."],
      ["환경 보호가 시급합니다.", "Environmental protection is urgent."],
      ["기후 변화는 심각한 문제입니다.", "Climate change is a serious issue."],
      ["재활용에 동참해야 합니다.", "We should take part in recycling."],
      ["지속 가능한 발전이 필요합니다.", "We need sustainable development."],
      ["사회적 책임이 중요합니다.", "Social responsibility matters."],
      ["다양성을 존중합시다.", "Let's respect diversity."],
      ["봉사활동에 참여하고 싶습니다.", "I'd like to participate in volunteer work."],
      ["지역사회에 기여하고 싶어요.", "I want to contribute to my community."],
      ["공공의 이익을 우선해야 합니다.", "We should prioritize the public interest."],
      ["역사를 잊지 말아야 합니다.", "We must not forget our history."],
    ],
  },
  {
    category: "토익 빈출 표현",
    items: [
      ["실례합니다만, 도와드릴까요?", "Excuse me, may I help you?"],
      ["몇 가지 질문드려도 될까요?", "May I ask you a few questions?"],
      ["이 자리는 비어 있나요?", "Is this seat taken?"],
      ["언제 시작하나요?", "When does it start?"],
      ["언제 끝나나요?", "When does it end?"],
      ["어디에서 만날까요?", "Where shall we meet?"],
      ["몇 시에 만날까요?", "What time shall we meet?"],
      ["얼마나 오래 걸리나요?", "How long will it take?"],
      ["저는 그것을 처리하고 있습니다.", "I'm working on it."],
      ["전에 한 번 해본 적이 있어요.", "I've done it once before."],
      ["거의 끝나갑니다.", "I'm almost done."],
      ["검토할 시간이 더 필요합니다.", "I need more time to review."],
      ["일정을 다시 잡아야 할 것 같습니다.", "I think we need to reschedule."],
      ["가능한 한 빨리 알려 주세요.", "Please let me know as soon as possible."],
      ["천천히 해도 됩니다.", "Take your time."],
      ["저는 시간이 충분합니다.", "I have plenty of time."],
      ["다시 확인해 보겠습니다.", "Let me double-check."],
      ["서류 작업이 많아요.", "There's a lot of paperwork."],
      ["예약을 변경하고 싶습니다.", "I'd like to change my reservation."],
      ["환불이 가능한가요?", "Is a refund possible?"],
      ["배달이 늦어지고 있습니다.", "The delivery is delayed."],
      ["문의해 보고 알려드리겠습니다.", "I'll check and get back to you."],
      ["담당자가 자리에 없습니다.", "The person in charge is not available."],
      ["메모를 남겨 두겠습니다.", "I'll leave a note."],
      ["회의가 연기되었습니다.", "The meeting has been postponed."],
      ["사무실로 와 주시겠어요?", "Could you come to the office?"],
      ["정확한 시간을 알려 주세요.", "Please tell me the exact time."],
      ["일정이 비어 있습니다.", "My schedule is open."],
      ["지금 통화 가능합니다.", "I can talk now."],
      ["급한 일이 생겼습니다.", "Something urgent came up."],
    ],
  },
];

const all: InsertToeic[] = [];
let no = 1;
for (const g of groups) {
  for (const [ko, en] of g.items) {
    all.push({
      sentenceNo: no++,
      category: g.category,
      korean: ko,
      english: en,
      practiceCount: 0,
      masteryLevel: 0,
      bookmarked: false,
    });
  }
}

export const toeicSeed = all;
