// 페파피그(Peppa Pig) 주요 에피소드 시드 데이터
// 영어 입문자 쉐도잉용으로 자주 추천되는 시즌 1-3 에피소드 위주
import type { InsertPeppa } from "@shared/schema";

export const peppaSeed: InsertPeppa[] = [
  // Season 1 — 영어 학습용 표준 추천
  { season: 1, episode: 1, titleEn: "Muddy Puddles", titleKo: "진흙 웅덩이", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 2, titleEn: "Mr Dinosaur is Lost", titleKo: "공룡 인형을 잃어버렸어요", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 3, titleEn: "Best Friend", titleKo: "단짝 친구", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 4, titleEn: "Polly Parrot", titleKo: "앵무새 폴리", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 5, titleEn: "Hide and Seek", titleKo: "숨바꼭질", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 6, titleEn: "The Playgroup", titleKo: "유치원", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 7, titleEn: "Mummy Pig at Work", titleKo: "엄마 돼지의 일터", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 8, titleEn: "Piggy in the Middle", titleKo: "가운데 돼지", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 9, titleEn: "Daddy Loses His Glasses", titleKo: "아빠가 안경을 잃어버렸어요", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 10, titleEn: "Gardening", titleKo: "정원 가꾸기", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 11, titleEn: "Hiccups", titleKo: "딸꾹질", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 12, titleEn: "Bicycles", titleKo: "자전거", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 13, titleEn: "Secrets", titleKo: "비밀", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 14, titleEn: "The School Fete", titleKo: "학교 축제", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 15, titleEn: "My Cousin Chloé", titleKo: "사촌 클로에", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 16, titleEn: "Not Very Well", titleKo: "아파요", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 17, titleEn: "Polly's Holiday", titleKo: "폴리의 휴가", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 18, titleEn: "School Play", titleKo: "학예회", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 19, titleEn: "The Tooth Fairy", titleKo: "이의 요정", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 1, episode: 20, titleEn: "The New Car", titleKo: "새 자동차", watchedCount: 0, shadowedCount: 0, status: "pending" },
  // Season 2
  { season: 2, episode: 1, titleEn: "Bubbles", titleKo: "비눗방울", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 2, episode: 2, titleEn: "Teddy's Day Out", titleKo: "테디의 외출", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 2, episode: 3, titleEn: "Mister Skinnylegs", titleKo: "다리가 가는 거미", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 2, episode: 4, titleEn: "Camping", titleKo: "캠핑", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 2, episode: 5, titleEn: "The Sleepover", titleKo: "친구 집에서 자기", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 2, episode: 6, titleEn: "Frogs and Worms and Butterflies", titleKo: "개구리, 벌레, 나비", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 2, episode: 7, titleEn: "The Tree House", titleKo: "나무집", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 2, episode: 8, titleEn: "The Camper Van", titleKo: "캠핑카", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 2, episode: 9, titleEn: "School Bus Trip", titleKo: "학교 견학", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 2, episode: 10, titleEn: "Rock Pools", titleKo: "바위 웅덩이", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 2, episode: 11, titleEn: "The Library", titleKo: "도서관", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 2, episode: 12, titleEn: "Daddy Pig's Office", titleKo: "아빠 돼지의 사무실", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 2, episode: 13, titleEn: "George's Friend", titleKo: "조지의 친구", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 2, episode: 14, titleEn: "Dens", titleKo: "비밀 기지", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 2, episode: 15, titleEn: "Recycling", titleKo: "재활용", watchedCount: 0, shadowedCount: 0, status: "pending" },
  // Season 3
  { season: 3, episode: 1, titleEn: "Work and Play", titleKo: "일과 놀이", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 3, episode: 2, titleEn: "The Eye Test", titleKo: "시력 검사", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 3, episode: 3, titleEn: "Daddy Pig's Birthday", titleKo: "아빠 돼지 생일", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 3, episode: 4, titleEn: "Cleaning the Car", titleKo: "세차하기", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 3, episode: 5, titleEn: "Pancakes", titleKo: "팬케이크", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 3, episode: 6, titleEn: "Daddy's Movie Camera", titleKo: "아빠의 비디오 카메라", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 3, episode: 7, titleEn: "The Cuckoo Clock", titleKo: "뻐꾸기 시계", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 3, episode: 8, titleEn: "Foggy Day", titleKo: "안개 낀 날", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 3, episode: 9, titleEn: "Children in Charge", titleKo: "아이들이 주인공", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 3, episode: 10, titleEn: "Grampy Rabbit's Boatyard", titleKo: "할아버지 토끼의 조선소", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 3, episode: 11, titleEn: "Granny Pig's Chickens", titleKo: "할머니 돼지의 닭들", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 3, episode: 12, titleEn: "Goldie the Fish", titleKo: "금붕어 골디", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 3, episode: 13, titleEn: "Mr Fox's Shop", titleKo: "여우 아저씨의 가게", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 3, episode: 14, titleEn: "The Boat Pond", titleKo: "보트 연못", watchedCount: 0, shadowedCount: 0, status: "pending" },
  { season: 3, episode: 15, titleEn: "George Catches a Cold", titleKo: "조지가 감기에 걸렸어요", watchedCount: 0, shadowedCount: 0, status: "pending" },
];
